// Mock data for the homepage. Will be replaced by API calls (Phase: search/booking).

const img = (id, w = 800, h = 600) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

// Quick-pick neighbourhoods / areas shown under the hero search bar
export const QUICK_AREAS = [
  'Alger Centre',
  'Hydra',
  'Bab Ezzouar',
  'Oran',
  'Constantine',
  'Annaba',
  'Sétif',
  'Béjaïa',
];

// Hotel "types" used as category filter circles
export const CATEGORIES = [
  { name: 'Tous', img: img('1564501049412-61c2a3083791') },
  { name: 'Luxe', img: img('1566073771259-6a8506099945') },
  { name: 'Affaires', img: img('1551882547-ff40c63fe5fa') },
  { name: 'Balnéaire', img: img('1520250497591-112f2f40a3f4') },
  { name: 'Riad', img: img('1582719478250-c89cae4dc85b') },
  { name: 'Boutique', img: img('1611892440504-42a792e24d32') },
  { name: 'Montagne', img: img('1455587734955-081b22074882') },
  { name: 'Désert', img: img('1469474968028-56623f02e42e') },
  { name: 'Appart-hôtel', img: img('1502672260266-1c1ef2d93688') },
  { name: 'Économique', img: img('1445019980597-93fa8acb246c') },
];

// Cities with hotel counts (Découvrez par ville)
export const CITIES = [
  { name: 'Alger', count: 362, img: img('1583422409516-2895a77efded') },
  { name: 'Oran', count: 118, img: img('1590490360182-c33d57733427') },
  { name: 'Constantine', count: 64, img: img('1539037116277-4db20889f2d4') },
  { name: 'Sétif', count: 37, img: img('1502602898657-3e91760cbb34') },
  { name: 'Annaba', count: 28, img: img('1512453979798-5ea266f8880c') },
  { name: 'Tlemcen', count: 21, img: img('1518684079-3c830dcef090') },
];

// Featured hotels (En Vedette)
export const FEATURED = [
  {
    id: 'h1',
    name: 'Sofitel Algiers Hamma',
    city: 'Alger',
    img: img('1566073771259-6a8506099945'),
  },
  {
    id: 'h2',
    name: 'Le Méridien Oran',
    city: 'Oran',
    img: img('1571896349842-33c89424de2d'),
  },
  {
    id: 'h3',
    name: 'Marriott Constantine',
    city: 'Constantine',
    img: img('1582719508461-905c673771fd'),
  },
  {
    id: 'h4',
    name: 'Riad El Kahina',
    city: 'Tlemcen',
    img: img('1578683010236-d716f9a3f461'),
  },
  {
    id: 'h5',
    name: 'Hôtel Saint George',
    city: 'Alger',
    img: img('1564501049412-61c2a3083791'),
  },
];

// Hotel list grid
export const HOTELS = [
  {
    id: 'h1',
    name: 'Sofitel Algiers Hamma',
    city: 'Alger',
    type: 'Luxe',
    price: 24500,
    stars: 5,
    rating: 4.6,
    reviews: 412,
    img: img('1566073771259-6a8506099945'),
  },
  {
    id: 'h2',
    name: 'Le Méridien Oran',
    city: 'Oran',
    type: 'Affaires',
    price: 19800,
    stars: 5,
    rating: 4.4,
    reviews: 285,
    img: img('1571896349842-33c89424de2d'),
  },
  {
    id: 'h3',
    name: 'Marriott Constantine',
    city: 'Constantine',
    type: 'Affaires',
    price: 17500,
    stars: 5,
    rating: 4.3,
    reviews: 198,
    img: img('1582719508461-905c673771fd'),
  },
  {
    id: 'h4',
    name: 'Riad El Kahina',
    city: 'Tlemcen',
    type: 'Riad',
    price: 9800,
    stars: 4,
    rating: 4.1,
    reviews: 96,
    img: img('1578683010236-d716f9a3f461'),
  },
  {
    id: 'h5',
    name: 'Hôtel Saint George',
    city: 'Alger',
    type: 'Boutique',
    price: 14200,
    stars: 4,
    rating: 4.5,
    reviews: 320,
    img: img('1564501049412-61c2a3083791'),
  },
  {
    id: 'h6',
    name: 'Sheraton Club des Pins',
    city: 'Alger',
    type: 'Balnéaire',
    price: 21000,
    stars: 5,
    rating: 4.2,
    reviews: 510,
    img: img('1520250497591-112f2f40a3f4'),
  },
  {
    id: 'h7',
    name: 'Gourara Timimoun',
    city: 'Timimoun',
    type: 'Désert',
    price: 8600,
    stars: 3,
    rating: 4.0,
    reviews: 64,
    img: img('1469474968028-56623f02e42e'),
  },
  {
    id: 'h8',
    name: 'Tikjda Resort',
    city: 'Bouira',
    type: 'Montagne',
    price: 7200,
    stars: 3,
    rating: 3.9,
    reviews: 47,
    img: img('1455587734955-081b22074882'),
  },
];

export const formatDZD = (n) =>
  new Intl.NumberFormat('fr-DZ').format(n) + ' DZD';

export const TRANSLATIONS = {
  fr: {
    navHome: 'Accueil',
    navHotels: 'Hôtels DZ',
    navHouses: 'Maisons DZ',
    navDestinations: 'Destinations',
    navPricing: 'Tarifs',
    navSales: 'Ventes',
    suggestHotel: 'Suggérer un hôtel',
    mySpace: 'Mon espace',
    login: 'Connexion',
    signUp: "S'inscrire",
    favorites: 'Favoris',
    tagline: "Séjournez l'Algérie",
    heroTitle: "Trouvez votre séjour idéal en Algérie",
    heroSubtitle: "Hôtels de luxe, maisons traditionnelles, appartements et riads dans les 58 wilayas",
    searchDestination: "Où souhaitez-vous aller ?",
    searchWilayaPlaceholder: "Wilaya ou ville (ex: Alger, Oran...)",
    checkIn: "Arrivée",
    checkOut: "Départ",
    searchBtn: "Rechercher",
    discoverByCity: "Découvrez par ville",
    discoverSubtitle: "Explorez les meilleurs hôtels et maisons de chaque ville",
    showAllCities: "Afficher toutes les villes",
    hotelsCount: "hôtels",
    featuredHotels: "Hôtels en vedette",
    featuredHotelsSubtitle: "Les établissements les mieux notés en Algérie",
    featuredHouses: "Locations de Maisons",
    featuredHousesSubtitle: "Villas, chalets, appartements en Algérie",
    featuredSales: "Biens Immobiliers à Vendre",
    featuredSalesSubtitle: "Villas, appartements et terrains à acheter en Algérie",
    seeAll: "Voir toutes",
    perNight: "/nuit",
    noHousesCity: "Aucune maison disponible dans cette ville.",
    noHotelsCity: "Aucun hôtel disponible dans cette catégorie ou ville.",
    quickLinks: "Liens rapides",
    explore: "Explorer",
    gallery: "Galerie",
    address: "Adresse",
    email: "Email",
    phone: "Téléphone",
    subscribe: "S'abonner",
    subscribed: "Inscrit !",
    emailPlaceholder: "Votre adresse email",
    footerDesc: "Réservez les meilleurs hôtels et maisons dans les 58 wilayas d'Algérie.",
    becomeOwner: "Devenir hôtelier",
    myBookings: "Mes réservations",
    helpCenter: "Centre d'aide",
    copyright: "Tous droits réservés.",
  },
  ar: {
    navHome: 'الرئيسية',
    navHotels: 'فنادق الجزائر',
    navHouses: 'منازل للكراء',
    navDestinations: 'الوجهات',
    navPricing: 'الأسعار',
    navSales: 'عقارات للبيع',
    suggestHotel: 'إضافة فندق',
    mySpace: 'حسابي',
    login: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    favorites: 'المفضلة',
    tagline: 'إقامتك في الجزائر',
    heroTitle: 'اعثر على إقامتك المثالية في الجزائر',
    heroSubtitle: 'فنادق فاخرة، منازل تقليدية، شقق ورياض في 58 ولاية',
    searchDestination: 'أين تريد الذهاب؟',
    searchWilayaPlaceholder: 'الولاية أو المدينة (مثال: الجزائر، وهران...)',
    checkIn: 'تاريخ الوصول',
    checkOut: 'تاريخ المغادرة',
    searchBtn: 'بحث',
    discoverByCity: 'استكشف حسب المدينة',
    discoverSubtitle: 'استكشف أفضل الفنادق والمنازل في كل مدينة',
    showAllCities: 'عرض جميع المدن',
    hotelsCount: 'فنادق',
    featuredHotels: 'فنادق مميزة',
    featuredHotelsSubtitle: 'الأعلى تقييماً في الجزائر',
    featuredHouses: 'منازل ومنازل للكراء',
    featuredHousesSubtitle: 'فيلا، شاليهات، وشقق في الجزائر',
    featuredSales: 'عقارات للبيع',
    featuredSalesSubtitle: 'شقق، فيلات، وأراضي للبيع في الجزائر',
    seeAll: 'عرض الكل',
    perNight: '/ليلة',
    noHousesCity: 'لا تتوفر منازل في هذه المدينة حالياً.',
    noHotelsCity: 'لا تتوفر فنادق في هذه الفئة أو المدينة حالياً.',
    quickLinks: 'روابط سريعة',
    explore: 'استكشاف',
    gallery: 'معرض الصور',
    address: 'العنوان',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    subscribe: 'اشتراك',
    subscribed: 'تم الاشتراك!',
    emailPlaceholder: 'بريدك الإلكتروني',
    footerDesc: 'احجز أفضل الفنادق والمنازل في 58 ولاية جزائرية.',
    becomeOwner: 'أضف عقارك',
    myBookings: 'حجوزاتي',
    helpCenter: 'مركز المساعدة',
    copyright: 'جميع الحقوق محفوظة.',
  },
  en: {
    navHome: 'Home',
    navHotels: 'DZ Hotels',
    navHouses: 'Houses',
    navDestinations: 'Destinations',
    navPricing: 'Pricing',
    navSales: 'For Sale',
    suggestHotel: 'List a Property',
    mySpace: 'My Space',
    login: 'Login',
    signUp: 'Sign Up',
    favorites: 'Favorites',
    tagline: 'Stay in Algeria',
    heroTitle: 'Find Your Perfect Stay in Algeria',
    heroSubtitle: 'Luxury hotels, traditional houses, apartments, and riads across all 58 provinces',
    searchDestination: 'Where do you want to go?',
    searchWilayaPlaceholder: 'Province or city (e.g. Algiers, Oran...)',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    searchBtn: 'Search',
    discoverByCity: 'Explore by City',
    discoverSubtitle: 'Discover the top-rated hotels & houses in every city',
    showAllCities: 'Show all cities',
    hotelsCount: 'hotels',
    featuredHotels: 'Featured Hotels',
    featuredHotelsSubtitle: 'The highest-rated accommodations in Algeria',
    featuredHouses: 'House Rentals',
    featuredHousesSubtitle: 'Villas, chalets, and apartments in Algeria',
    featuredSales: 'Properties For Sale',
    featuredSalesSubtitle: 'Villas, apartments, and land for purchase in Algeria',
    seeAll: 'View all',
    perNight: '/night',
    noHousesCity: 'No houses available in this city.',
    noHotelsCity: 'No hotels available in this category or city.',
    quickLinks: 'Quick Links',
    explore: 'Explore',
    gallery: 'Gallery',
    address: 'Address',
    email: 'Email',
    phone: 'Phone',
    subscribe: 'Subscribe',
    subscribed: 'Subscribed!',
    emailPlaceholder: 'Your email address',
    footerDesc: 'Book the best hotels and houses across Algeria’s 58 provinces.',
    becomeOwner: 'Become a Host',
    myBookings: 'My Bookings',
    helpCenter: 'Help Center',
    copyright: 'All rights reserved.',
  },
};
